---
title: "Pacto del contribuyente"
output: html_document

lang: es
date: 14/feb/2025
categories: [taller]
format: 
  html:
    toc: true
---

## Código de Conducta Convenido 

### Nuestro compromiso

En el interés de fomentar una comunidad abierta y acogedora, nosotros como participantes y facilitadores nos comprometemos a hacer de la participación en nuestro taller y nuestra comunidad una experiencia libre de acoso para todos, independientemente de la edad, dimensión corporal, discapacidad, etnia, identidad y expresión de género, nivel de experiencia, nacionalidad, apariencia física, raza, religión, identidad u orientación sexual. 

### Nuestros estándares

Ejemplos de comportamiento que contribuyen a crear un ambiente positivo:

* Uso de lenguaje amable e inclusivo
* Respeto a diferentes puntos de vista y experiencias
* Aceptación de críticas constructivas
* Enfocarse en lo que es mejor para la comunidad
* Mostrar empatía a otros miembros de la comunidad

Ejemplos de comportamiento inaceptable por participantes:

* Uso de lenguaje o imágenes sexuales y atención sexual no deseada
* Comentarios insultantes o despectivos (*trolling*) y ataques personales o políticos
* Acoso público o privado
* Publicación de información privada de terceros sin su consentimiento, como direcciones físicas o electrónicas
* Otros tipos de conducta que pudieran considerarse inapropiadas en un entorno profesional.

### Nuestras responsabilidades

Los facilitadores del taller son responsables de clarificar los estándares de comportamiento aceptable y se espera que tomen medidas correctivas y apropiadas en respuesta a situaciones de conducta inaceptable. 

Los facilitadores del taller tienen el derecho y la responsabilidad de eliminar en los productos para la Web que se elaboren, editar o rechazar comentarios, *commits*, código, ediciones de documentación, *issues*, y otras contribuciones que no estén alineadas con este Código de Conducta, o de prohibir temporal o permanentemente a cualquier participante cuyo comportamiento sea inapropiado, amenazante, ofensivo o perjudicial.

### Alcance

Este código de conducta aplica tanto a espacios del taller como a espacios públicos donde un individuo presente intereses del taller o comunidad UV. Ejemplos de esto incluye el uso de correo electrónico a nombre del grupo, publicaciones a través de las redes sociales, o presentaciones en eventos *online* u *offline*. La representación del taller puede ser clarificada explicitamente por los facilitadores del proyecto.
 
### Aplicación

Ejemplos de abuso, acoso u otro tipo de comportamiento inaceptable puede ser reportado al conductor del taller en [M. Equihua](mailto:equihuam@gmail.com). Todas las quejas serán revisadas e investigadas, generando un resultado apropiado a las circunstancias. El equipo del proyecto está obligado a mantener confidencialidad de la persona que reportó el incidente. Detalles específicos acerca de las políticas de aplicación pueden ser publicadas por separado.

Facilitadores que no sigan o que no hagan cumplir este Código de Conducta pueden ser eliminados de forma temporal o permanente del equipo. 

### Atribución

Este Código de Conducta es una adaptación del Contributor Covenant, versión 1.4, disponible en [https://www.contributor-covenant.org/es/version/1/4/code-of-conduct.html](https://www.contributor-covenant.org/es/version/1/4/code-of-conduct.html)
