---
title: "Datos abiertos"
editor_options: 
  chunk_output_type: console
---



## Catálogo de datos en [datos.gob.mx](datos.gob.mx)

```{r}
pacman::p_load(httr2, jsonlite, tidyverse, DT)

req <- request("https://api.datos.gob.mx/v1/api-catalog?pageSize=8000")
resp <- req_perform(req)

dat_1 <- fromJSON(resp_body_string(resp))
dat_1_df <- dat_1$results

for (i in 1:length(dat_1_df$variables))
{
  dat_1_df$variables[i] <- paste(dat_1_df$variables[[i]], collapse = ",")
}

dat_1_df$variables <- unlist(dat_1_df$variables)

dat_1_df |>
  select("endpoint", "url", "variables") |> 
  datatable()

```

## Ozono

```{r}
url <- "https://api.datos.gob.mx/v2/sinaica?pageSize=8000&parametro=O3&estacionesid=259&page=1"

req_O3 <- request(url)
resp_O3 <- req_perform(req)

dat_O3 <- fromJSON(resp_body_string(resp_O3))
dat_1_df <- dat_1$results

for (i in 1:length(dat_1_df$variables))
{
  dat_1_df$variables[i] <- paste(dat_1_df$variables[[i]], collapse = ",")
}

dat_1_df$variables <- unlist(dat_1_df$variables)

dat_1_df |>
  select("endpoint", "url", "variables") |> 
  datatable()

respuesta <- (url)

dat_O3 <- fromJSON(prettify(respuesta))

dat_O3_df <- as_tibble(dat_O3$results)


```


```{r}

url <- "https://smn.conagua.gob.mx/tools/RESOURCES/Normales_Climatologicas/Diarios/ver/dia30393.txt"

dat_meteo_meta <- readLines(url, n = 25)

# datos de la estación
estacion <- tibble(est = unlist(dat_meteo_meta[11:19]))

estacion <- estacion |> 
  mutate(var = str_extract(est, "(.*)(?=\\s:)"),
         val = str_extract(est, "(?<=\\s:)(.*)"),
         var = str_trim(var),
         val = str_trim(val), .keep = "unused" ) 

nombres <- estacion$var

estacion <- as_tibble(t(estacion[, 2]))
names(estacion) <- nombres

# variables meteorologicas
variables <- str_split(readLines(url, n = 24)[24], "\t")[[1]][c(1,3:6)]

# datos meteorológicos
dat_meteo <- read.csv(url, skip = 25, sep = "\t", header = F)
names(dat_meteo) <- variables

dat_meteo |> 
  mutate(idEstacion = estacion$ESTACIÓN)

```

```{r}
library(sf)
# retrive a list of every layer of the kmz file 
l_layers <- sf::st_read("../EstacionesClimatologicas/doc.kml", "Estaciones operativas")

l_layers$Description

```

